USE Adventureworks
GO

IF OBJECT_ID('PRODUTOS_N') IS NOT NULL
DROP TABLE PRODUTOS_N
GO

IF OBJECT_ID('VENDAS_N') IS NOT NULL
DROP TABLE VENDAS_N
GO


CREATE TABLE [dbo].[PRODUTOS_N]
(
	[ID] [int] IDENTITY PRIMARY KEY,
	[NOME] [varchar](50) NOT NULL,
	[PRECO] [numeric](8, 2) NOT NULL
) 
GO



CREATE TABLE [dbo].[VENDAS_N]
(
	[ID_VENDA] [int] IDENTITY PRIMARY KEY,
	[ID_PRODUTO] [int] NOT NULL,
	[QUANTIDADE] [int] NOT NULL
) 

ALTER TABLE [dbo].[VENDAS_N]  WITH CHECK ADD  CONSTRAINT [FK_VENDAS_N_PRODUTOS_N] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[PRODUTOS_N] ([ID])
GO

ALTER TABLE [dbo].[VENDAS_N] CHECK CONSTRAINT [FK_VENDAS_N_PRODUTOS_N]
GO

SELECT * FROM PRODUTOS_N 

INSERT INTO PRODUTOS_N 
VALUES ('MOUSE',15.00),('TECLADO',20.00),('MONITOR LED',380.00),('ESTABILIZADOR',35.00)


SELECT * FROM VENDAS_N

INSERT INTO VENDAS_N
VALUES (1,10),(2,20)

-- VIOLACAO DE INTEGRIDADE REFERENCIAL
INSERT INTO VENDAS_N
VALUES (111,10)



DELETE PRODUTOS_N WHERE ID = 1


--DROP TRIGGER [tgCASCADE_PRODUTOS]

CREATE TRIGGER [tgCASCATA_PRODUTOS] 
ON [dbo].[PRODUTOS_N]
INSTEAD OF delete AS
BEGIN
    SET NOCOUNT ON;
    
	DELETE FROM VENDAS_N 
	WHERE ID_PRODUTO = (SELECT ID FROM deleted)
	
    DELETE FROM PRODUTOS_N
	WHERE ID = (SELECT ID FROM deleted)
	
	SET NOCOUNT OFF;

END;


--delete from PRODUTOS_N
--select * from PRODUTOS_N

DELETE FROM dbo.PRODUTOS_N
WHERE ID = 10





-- DROP TRIGGER [tglen_PRODUTOS]
CREATE TRIGGER [tglen_PRODUTOS_N]
   ON  PRODUTOS_N
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @name nvarchar(50)
	SELECT @name = NOME
	FROM inserted
	IF len(@name) < 5 
	BEGIN
		ROLLBACK TRANSACTION
	END
	SET NOCOUNT OFF;
	
END

INSERT INTO PRODUTOS_N VALUES ('PRODUTO999',10.55)

INSERT INTO PRODUTOS_N VALUES ('ABC',9.99)



--CREATE TRIGGER [tg_JobCandidate] 
--ON [HumanResources].[JobCandidate]
--after delete AS
----instead of update
--BEGIN
--	ROLLBACK
--END;

----delete from HumanResources.JobCandidate 

--select * from HumanResources.JobCandidate 
